"""Generate the two variable-selection exhibits:
  tables/tab_weather_sel.tex - E1: mean leave-one-out dAIC per candidate
      weather covariate, on M0 / M1 / M2 (drop from the full 5-variable set;
      positive = dropping worsens fit), with the keep/drop decision.
  tables/tab_grid_sel.tex    - E2: ANOVA decomposition (%) of the fully
      interacted DiD coefficients, mean over modes, on M1 (fixed effects)
      and M2 (random slopes on the 225-cell grid).
Inputs: results/weather_sweep__tw79.csv, weather_sweep_m0m1__tw79.csv,
        decomp_m1_cells_dow__tw79.csv, decomp_m2_blups_dow__tw79.csv"""
import os
import numpy as np, pandas as pd
from fig_style import RESULTS, TABDIR

VARS = ["temperature_2m", "rain", "snowfall", "wind_gusts_10m", "relative_humidity_2m"]
NAME = {"temperature_2m": "temperature", "rain": "rain", "snowfall": "snowfall",
        "wind_gusts_10m": "wind gusts", "relative_humidity_2m": "relative humidity"}
ADOPT = {"temperature_2m", "wind_gusts_10m", "relative_humidity_2m"}
FULL = "+".join(VARS)

def loo(df):
    """mean over modes of AIC(drop v) - AIC(full), per candidate v"""
    a = df.groupby(["mode", "vars"]).AIC.first().reset_index()
    full = a[a.vars == FULL].set_index("mode").AIC
    out = {}
    for v in VARS:
        sub = a[a.vars.apply(lambda s: s != "none" and set(s.split("+")) == set(VARS) - {v})]
        out[v] = (sub.set_index("mode").AIC - full).mean()
    return out

m2 = pd.read_csv(os.path.join(RESULTS, "weather_sweep__tw79.csv"))
m01 = pd.read_csv(os.path.join(RESULTS, "weather_sweep_m0m1__tw79.csv"))
L = {"M0": loo(m01[m01.model == "M0"]), "M1": loo(m01[m01.model == "M1"]), "M2": loo(m2)}

rows = []
for v in VARS:
    dec = "keep" if v in ADOPT else "drop"
    net = L["M0"][v] + L["M1"][v] + L["M2"][v]
    rows.append(f"{NAME[v]} & {L['M0'][v]:+.1f} & {L['M1'][v]:+.1f} & "
                f"{L['M2'][v]:+.1f} & {net:+.1f} & {dec} \\\\")
body = "\n".join(rows)
with open(os.path.join(TABDIR, "tab_weather_sel.tex"), "w", encoding="utf-8") as f:
    f.write(rf"""% E1 -- weather covariate selection (generated by gen_selection_tables.py)
{{\scriptsize
\begin{{tabular}}{{@{{}}l ccc cc@{{}}}}
\toprule
 & \multicolumn{{3}}{{c}}{{mean $\Delta$AIC when dropped (ML refits)}} & & \\
\cmidrule(lr){{2-4}}
candidate covariate & M0 & M1 & M2 & net & decision \\
\midrule
{body}
\bottomrule
\end{{tabular}}}}
""")
print("saved tables/tab_weather_sel.tex")

# ---------------- E2: grid decomposition (r x s x p x d), M1 vs M2 ----------------
from itertools import combinations
AXES = (0, 1, 2, 3)                                    # 0=r, 1=s, 2=p, 3=d
SUBSETS = [S for k in range(1, 5) for S in combinations(AXES, k)]

def anova4(u):
    """u shape (5 flow, 3 season, 3 peak, 5 dow). Balanced 4-way ANOVA:
    15 orthogonal component shares (%) + 4 equal-split block shares (%)."""
    dims = u.shape; g = u.mean(); tot = u.size
    eff = {}
    for S in SUBSETS:
        other = tuple(a for a in AXES if a not in S)
        e = u.mean(axis=other) - g
        for T in eff:
            if set(T) < set(S):
                e = e - eff[T].reshape([dims[a] if a in T else 1 for a in S])
        eff[S] = e
    SS = {S: (tot / np.prod([dims[a] for a in S])) * np.sum(eff[S] ** 2) for S in SUBSETS}
    z = 100 / ((u - g) ** 2).sum()
    comp = [z * SS[S] for S in SUBSETS]
    blk = [z * sum(SS[S] / len(S) for S in SUBSETS if a in S) for a in AXES]
    return comp, blk

def mean_anova(df, val):
    comps, blks = [], []
    for m, g in df.groupby("mode"):
        u = (g.sort_values(["ring_flow", "season3", "peak", "dow"])[val]
             .to_numpy().reshape(5, 3, 3, 5))
        c, b = anova4(u); comps.append(c); blks.append(b)
    return np.mean(comps, axis=0), np.mean(blks, axis=0)

m1_comp, m1_blk = mean_anova(
    pd.read_csv(os.path.join(RESULTS, "decomp_m1_cells_dow__tw79.csv")), "coef")
m2_comp, m2_blk = mean_anova(
    pd.read_csv(os.path.join(RESULTS, "decomp_m2_blups_dow__tw79.csv")), "blup")

CN = [r"ring pair $r$", r"season $s$", r"peak $p$", r"day-of-week $d$",
      r"$r\times s$", r"$r\times p$", r"$r\times d$",
      r"$s\times p$", r"$s\times d$", r"$p\times d$",
      r"$r\times s\times p$", r"$r\times s\times d$",
      r"$r\times p\times d$", r"$s\times p\times d$",
      r"$r\times s\times p\times d$"]
def row(n, a, b, bold=False):
    if bold:
        return (rf"\textbf{{\boldmath {n}}} & \textbf{{{a:.1f}\%}} & "
                rf"\textbf{{{b:.1f}\%}} \\")
    return rf"{n} & {a:.1f}\% & {b:.1f}\% \\"
lines = [row(n, a, b, bold=(n == r"$r\times p$"))
         for n, a, b in zip(CN, m1_comp, m2_comp)]
lines.append(r"\midrule")
for n, a, b in zip([r"ring (aggregated)", r"peak (aggregated)",
                    r"season (aggregated)", r"day-of-week (aggregated)"],
                   [m1_blk[0], m1_blk[2], m1_blk[1], m1_blk[3]],
                   [m2_blk[0], m2_blk[2], m2_blk[1], m2_blk[3]]):
    lines.append(row(n, a, b, bold=n in (r"ring (aggregated)", r"peak (aggregated)")))
body = "\n".join(lines)
with open(os.path.join(TABDIR, "tab_grid_sel.tex"), "w", encoding="utf-8") as f:
    f.write(rf"""% E2 -- DiD interaction-grid selection (generated by gen_selection_tables.py)
{{\scriptsize
\begin{{tabular}}{{@{{}}l cc@{{}}}}
\toprule
share of total variation & M1 (fixed effects) & M2 (random slopes) \\
\midrule
{body}
\bottomrule
\end{{tabular}}}}
""")
print("saved tables/tab_grid_sel.tex")
