"""
Generate the three LaTeX tables for paper_tw79 (booktabs fragments, \input-ready):
  tables/tab_m2_reproduces.tex   - M2 reproduces M0 & M1.1.4 (equality t-tests)
  tables/tab_parallel_trends.tex - parallel-trends test outcomes by mode (RDST vs mean test)
  tables/tab_m2_full.tex         - full M2 results: raw estimates, 95% CI, p; variance components
Inputs: results/{integration_pvals,fixed,table3,gate_rst_ptr,varcomp,fitstats,did_blup}__tw79.csv
"""
import os
import pandas as pd
import numpy as np
from scipy import stats
from fig_style import RESULTS, TABDIR, MODES, MODE_LABEL, PEAK_SHORT, rp

TAG = "tw79"
def R(name):
    return pd.read_csv(os.path.join(RESULTS, f"{name}__{TAG}.csv"))

def fmt(x, d=3):
    return f"{x:.{d}f}"

def fmtp(p):
    return "$<$0.001" if p < 0.001 else f"{p:.3f}"

def write(name, s):
    path = os.path.join(TABDIR, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(s)
    print("saved tables/" + name)

# ---------------- T1: M2 reproduces M0 & M1.1.4 ----------------
ip = R("integration_pvals").set_index("mode")
fx = R("fixed")
b2 = fx[fx.term == "PostTreated"].set_index("mode")
flowcols = [c for c in ip.columns if "@" in c]

def collab(c):
    f, pk = c.split("@")
    return f.replace("->", "$\\to$") + " " + PEAK_SHORT[pk]

rows = []
for m in MODES:
    pv = [float(ip.loc[m, "pooled"])] + [float(ip.loc[m, c]) for c in flowcols]
    n_ns = sum(p >= 0.05 for p in pv)
    cells = " & ".join(f"{p:.3f}" for p in pv)   # CSV precision; no double rounding
    rows.append(f"{MODE_LABEL[m]} & {cells} & {n_ns}/16 \\\\")
heads = ["pooled"] + [collab(c) for c in flowcols] + [r"not sig.\ diff."]
headrow = "mode & " + " & ".join(rf"\rotatebox{{90}}{{{h}}}" for h in heads) + r" \\"
body = "\n".join(rows)
write("tab_m2_reproduces.tex", rf"""% T1 -- M2 reproduces M0 & M1.1 (generated by gen_tables.py)
{{\scriptsize\setlength{{\tabcolsep}}{{3pt}}
\begin{{tabular}}{{@{{}}l*{{17}}{{c}}@{{}}}}
\toprule
{headrow}
\midrule
{body}
\bottomrule
\end{{tabular}}}}
""")

# ---------------- T2: parallel-trends test outcomes ----------------
t3 = R("table3").set_index("mode")
g = R("gate_rst_ptr")
fails = g[~g.rst_pass]

def fail_str(m):
    d = fails[fails["mode"] == m]
    if d.empty:
        return "---"
    parts = []
    for f, sub in d.groupby("ring_flow", sort=True):
        pk = ", ".join(PEAK_SHORT[p] for p in ["am_peak", "off_peak", "pm_peak"]
                       if p in set(sub.peak))
        arr = f.replace("->", "$\\to$")
        parts.append(f"{arr} ({pk})")
    return "; ".join(parts)

def pf(x):
    return "pass" if bool(x) else "fail"

rows = []
for m in MODES:
    r = t3.loc[m]
    rows.append(
        f"{MODE_LABEL[m]} & {pf(r.pooled_rdst_pass)} & {int(r.cell_rdst_pass)}/15 & "
        f"{fail_str(m)} & {pf(r.pooled_mean_pass)} & {int(r.cell_mean_pass)}/15 \\\\")
tot_rdst_pool = int(t3.pooled_rdst_pass.sum()); tot_mean_pool = int(t3.pooled_mean_pass.sum())
tot_rdst = int(t3.cell_rdst_pass.sum()); tot_mean = int(t3.cell_mean_pass.sum())
rows.append(r"\midrule")
rows.append(
    f"all modes & {tot_rdst_pool}/5 & {tot_rdst}/75 & --- & "
    f"{tot_mean_pool}/5 & {tot_mean}/75 \\\\")
body = "\n".join(rows)
write("tab_parallel_trends.tex", rf"""% T2 -- parallel-trends test outcomes by mode (generated by gen_tables.py)
{{\scriptsize
\begin{{tabular}}{{@{{}}lcclcc@{{}}}}
\toprule
 & \multicolumn{{3}}{{c}}{{RDST}} & \multicolumn{{2}}{{c}}{{\shortstack{{pre-period residual\\ difference mean test}}}} \\
\cmidrule(lr){{2-4}}\cmidrule(l){{5-6}}
mode & pooled & flows pass & failing flows & pooled & flows pass \\
\midrule
{body}
\bottomrule
\end{{tabular}}}}
""")

# ---------------- T10: full M2 results ----------------
vc = R("varcomp").set_index("mode")
fs = R("fitstats").set_index("mode")
TERMS = [("(Intercept)",            r"$\beta_0$ grand intercept"),
         ("PostTreated",            r"$\beta_1$ pooled DiD"),
         ("z_temperature_2m",       r"$\beta_2$ temperature"),
         ("z_wind_gusts_10m",       r"$\beta_3$ wind gusts"),
         ("z_relative_humidity_2m", r"$\beta_4$ relative humidity"),
         ("ammi",                   r"$\beta_5$ AMMI")]

bl = R("did_blup").set_index(["mode", "ring_flow", "peak"])
fxi = fx.set_index(["mode", "term"])
PEAKS = ["am_peak", "off_peak", "pm_peak"]

# one uniform block per coefficient: estimate on line 1, 95% CI on line 2,
# p on line 3 where it is defined (fixed effects; BLUPs have no p).
def coef_block(lines, label, est, lo, hi, p=None):
    lines.append(label + " & " + " & ".join(fmt(e) for e in est) + r" \\")
    lines.append(r"\quad 95\% CI & " +
                 " & ".join(f"[{fmt(a)}, {fmt(b)}]" for a, b in zip(lo, hi)) + r" \\")
    if p is not None:
        lines.append(r"\quad $p$ & " + " & ".join(fmtp(v) for v in p) + r" \\")
    lines.append(r"\addlinespace[1pt]")

lines = [r"\multicolumn{6}{@{}l}{\emph{fixed effects}} \\[1pt]"]
for term, label in TERMS:
    est, lo, hi, pv = [], [], [], []
    for m in MODES:
        r = fxi.loc[(m, term)]
        half = stats.t.ppf(0.975, r.df) * r.se
        est.append(r.est); lo.append(r.est - half); hi.append(r.est + half)
        pv.append(r.p)
    coef_block(lines, label, est, lo, hi, pv)

lines.append(r"\midrule")
lines.append(r"\multicolumn{6}{@{}l}{\emph{flow-level DiD coefficients "
             r"$\beta_1+u_{r,p}$}} \\[1pt]")
for f in ["0->0", "0->1", "0->2", "1->0", "2->0"]:
    for pk in PEAKS:
        est, lo, hi = [], [], []
        for m in MODES:
            r = bl.loc[(m, f, pk)]
            est.append(r.blup); lo.append(r.ci_lo); hi.append(r.ci_hi)
        arr = f.replace("->", "$\\to$")
        coef_block(lines, rf"{arr} {PEAK_SHORT[pk]}", est, lo, hi)

lines.append(r"\midrule")
lines.append(r"\multicolumn{6}{@{}l}{\emph{variance components and fit}} \\[1pt]")
for key, label in [("sigma2_r",  r"$\sigma_r^2$ ring-pair intercept"),
                   ("sigma2_t",  r"$\sigma_t^2$ time intercept"),
                   ("sigma2_rp", r"$\sigma_{rp}^2$ flow slope"),
                   ("sigma2_resid", r"$\sigma^2$ residual")]:
    lines.append(label + " & " +
                 " & ".join(fmt(vc.loc[m, key]) for m in MODES) + r" \\")
lines.append(r"\addlinespace[1pt]")
lines.append("AIC & " + " & ".join(fmt(fs.loc[m, "AIC"], 1) for m in MODES) + r" \\")
lines.append("BIC & " + " & ".join(fmt(fs.loc[m, "BIC"], 1) for m in MODES) + r" \\")

body = "\n".join(lines)
write("tab_m2_full.tex", rf"""% T10 -- full M2 results, raw estimates (generated by gen_tables.py)
{{\scriptsize
\begin{{tabular}}{{@{{}}l*{{5}}{{c}}@{{}}}}
\toprule
 & {' & '.join(MODE_LABEL[m] for m in MODES)} \\
\midrule
{body}
\bottomrule
\end{{tabular}}}}
""")

# (ring-descriptives table removed from this public release: it reads the ring-construction
#  intermediates, which are not part of this repository)

print("all tables done")
